name: aimara
favicon: null
layout_spectrum: 0
typography_spectrum: 0.62938
title: aimará en su nueva etapa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.569137142971158
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
